### PR TITLE
Lance wang12 hw1

### PR DESCRIPTION
**Pull request by LanceWang12**
- 310552021 王睿成 LanceWang12 hw1
- hw1 initialization
- from my `LanceWang12-hw1` branch merging to teacher's `hw1` branch

### CODE REVIEW

**Review by yungyuc — CHANGES_REQUESTED** [review]
Please do not include unrelated changesets.  See #2 for more information.

**Comment by yungyuc** [comment]
@LanceWang12 No, you didn't.  Please see #2 for more infromation.

**Comment by LanceWang12** [comment]
Sorry teacher, can I ask a question?  #2 mean I should remove the commit record right?  Specifically, what changesets mean?

**Comment by yungyuc** [comment]
Yes.  See https://stackoverflow.com/questions/38648491/what-is-a-changeset-in-git

**Pull request closed without merging**
