### PR TITLE
till22G-project-proposal-attempt2

### PR DESCRIPTION
**Pull request by till22G**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by till22G** [comment]
I made a new pullrequest for project proposal: old one can be found here: https://github.com/yungyuc/nsdhw_22au/pull/172

**Review by yungyuc — APPROVED** [review]
LGTM

**Comment by yungyuc** [comment]
> I made a new pullrequest for project proposal: old one can be found here: #172

Thanks for tagging the old PR.  It helps me keep track of your work.

**Comment by till22G** [comment]
Thank you for your support so far. I wrote a first version of the code. Should I still add it as a prototype to the proposal?

**Comment by yungyuc** [comment]
> Thank you for your support so far. I wrote a first version of the code. Should I still add it as a prototype to the proposal?

If you would like to have my review of your code, simply tag me in your project repository, not here.

**Pull request merged**
