### PR TITLE
Hooje hw2 attemp1

### PR DESCRIPTION
**Pull request by Hooje**
---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

### CODE REVIEW

**Comment by season06** [comment]
Please do not push files from other homework in PRs.
Only keep hw2, or you will lose your score.

**Comment by Hooje** [comment]
I don't know how that happened (only for 'project' directory, so weird).
So I just delete the 'project' directory in this branch and push.
Is it acceptable now?

**Comment by season06** [comment]
Please `rebase` to hw2.
You can google it to understand how to use it.

**Comment by Hooje** [comment]
Ok, I have changed something. 
Thanks.
Is it acceptable now?

**Pull request merged**
