### PR TITLE
Homework 2 Attempt 1

### PR DESCRIPTION
**Pull request by till22G**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by season06** [comment]
Please do not push files from other homework in PRs.
Only keep hw2, or you will lose your score.

**Comment by till22G** [comment]
Hello, I am sorry that happend. I will fix it in due time and do another pull request.

**Comment by till22G** [comment]
I updated the PR. I think I have a similar issue in the PR for hw2, but I did not just want to update it without permission from the TA or Lecurer. Should I also clean my HW1 PR? 

Best regards and thank you for the opportunity

**Comment by till22G** [comment]
Ok, than you.  I will fix the issues of homework 1 as soon as possible.

**Pull request merged**
