### PR TITLE
Hw1

### PR DESCRIPTION
**Pull request by till22G**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by till22G** [comment]
Hello, I was just checking if my merge was successfull and I saw that I did not get all the point, because some permissions where denied. I do not understand why, since I gave rwxrwxrwx permissions to all the files and folders. When I ran the validation locally, everything worked and I got full points.

**Comment by yungyuc** [comment]
> Hello, I was just checking if my merge was successfull and I saw that I did not get all the point, because some permissions where denied. I do not understand why, since I gave rwxrwxrwx permissions to all the files and folders. When I ran the validation locally, everything worked and I got full points.

What you pushed to the github does not match your description.  Please fix.  Further questions please find the grader.

```bash
$ ls -al hw1/till22G/
total 16
drwxr-xr-x  4 yungyuc  staff  128 Sep 21 20:00 ./
drwxr-xr-x  6 yungyuc  staff  192 Sep 21 20:00 ../
-rw-r--r--  1 yungyuc  staff  120 Sep 21 20:00 countline.py
-rw-r--r--  1 yungyuc  staff   24 Sep 21 20:00 countline.sh
```

**Comment by till22G** [comment]
Hello, thank you for the quick reply. I am sorry, I did not know I had to switch a filemode in the git project, so set permissions will not be ignored when pushing to github. I changed the filemode and the scripts run now. I hope this mistake does not prevent me from getting the points for the homework.

**Comment by till22G** [comment]
Hello, I changes all the files, so the PR should be correct now.

**Comment by yungyuc** [comment]
Please get rid of unrelated changesets before @season06 can merge it.

**Pull request closed without merging**
