### PR TITLE
hw1

### PR DESCRIPTION
**Pull request by haashiagh10**
test for hw1

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

### CODE REVIEW

**Comment by haashiagh10** [comment]
@yungyuc  When I upload and check the hw1 is correct or not. The check page and the grades part. It will tell me that permission denied , I want to know how to fix it.

**Comment by haashiagh10** [comment]
in line 11 of the grade

**Comment by yungyuc** [comment]
> in line 11 of the grade

Please provide the URL to the line.

**Comment by haashiagh10** [comment]
https://github.com/yungyuc/nsdhw_22au/pull/83/checks#step:5:12

**Comment by yungyuc** [comment]
What is the permission of the script files you uploaded?  Please make sure they have the executable bits set:

```bash
$ ls -al countline.sh
-rwxr-xr-x  1 yungyuc  staff  235 Jul 22 07:16 countline.sh*
```

**Pull request merged**
